name: Look Mart BD Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Connect to server and deploy
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/lookmart/admin.lookmartbd.com

            echo "Pull latest code"
            git pull origin main

            echo "Install composer dependencies"
            composer install --no-dev --optimize-autoloader

            echo "Run migrations"
            php artisan migrate --force

            echo "Clear caches"
            php artisan optimize:clear

            echo "Optimize Laravel"
            php artisan optimize
